name: sisumakerv2
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^0.1.3
  shimmer: ^1.0.1
  awesome_package: ^0.0.1
  equatable: ^1.0.3

  # Utils
  http: ^0.12.2
  rxdart: ^0.23.1
  shared_preferences: ^0.5.12+2

  # Bloc
  bloc: ^6.0.3
  flutter_bloc: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/
    - lib/assets/img/
    - lib/assets/

  fonts:
    - family: Satisfy-Regular
      fonts:
        - asset: lib/assets/fonts/Satisfy-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: lib/assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: lib/assets/fonts/ubuntu/Ubuntu-Bold.ttf
    # - family: Raleway
    #   fonts:
    #     - asset: packages/awesome_package/fonts/Raleway-Regular.ttf
    #     - asset: packages/awesome_package/fonts/Raleway-Italic.ttf
